project_id = "gtefgucwbskgknsdirvj"

[functions]
  [functions.send-push-notification]
    verify_jwt = false
  [functions.send-booking-reminder]
    verify_jwt = false
  [functions.create-booking]
    verify_jwt = false
  [functions.cancel-booking]
    verify_jwt = false
  [functions.send-booking-email]
    verify_jwt = false
  [functions.get-booking-by-token]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
