utorok 31. marca
14:30
15:30
60 min
Chiro masáž
Peter Šuca
+421949327276
sucapeter@gmail.com
Personál FYZIO&FIT
Potvrdené
streda 1. apríla
08:03
08:33
30 min
Express termín
TooLate Test
+421900111222
toolate@test.com
Potvrdené
09:00
09:30
30 min
Chiropraxia/Naprávanie
Erik Rusnak
+421904274287
e.rusnak.0@gmail.com
Personál FYZIO&FIT
Potvrdené
09:30
10:30
60 min
Chiro masáž
Albín Jančo
+421908087169
janco.albin@gmail.com
Personál FYZIO&FIT
Potvrdené
10:00
10:30
30 min
Express termín
TooLate Test2
+421900111222
toolate2@test.com
Potvrdené
10:30
12:00
90 min
Celotelová chiro masáž
Alžbeta Truhanová
+421949224889
truhanovaalzbeta@gmail.com
Personál FYZIO&FIT
Potvrdené
13:00
14:00
60 min
Chiro masáž
Daniel Hasara
0948 900 281
hasaradaniel@gmail.com
Personál FYZIO&FIT
Potvrdené
15:30
16:30
60 min
Chiro masáž
František Štofančík
+421948879150
fstofancik@gmail.com
Personál FYZIO&FIT
Potvrdené
štvrtok 2. apríla
09:30
10:00
30 min
Chiropraxia/Naprávanie
Robert Majdak
+421907945319
robomajdak@gmail.com
Personál FYZIO&FIT
Potvrdené
11:00
12:00
60 min
Chiro masáž
Martin Matasovsky
+421903934512
ing.matasovsky@gmail.com
Personál FYZIO&FIT
Potvrdené
12:00
13:30
90 min
Celotelová chiro masáž
Daniel Palenčík
0905456802
daniel.palencik@gmail.com
Personál FYZIO&FIT
Potvrdené
14:30
15:00
30 min
Chiropraxia/Naprávanie
Natália Jurčova
+421908200791
n.jurcova3104@gma.com
Personál FYZIO&FIT
Potvrdené
15:00
16:30
90 min
Celotelová chiro masáž
Peter Kolesár
+421919297111
wasko88@gmail.com
Personál FYZIO&FIT
Potvrdené
16:30
18:00
90 min
Celotelová chiro masáž
Lucia Straková
+421907057718
luciahudak@centrum.cz
Personál FYZIO&FIT
Potvrdené
18:00
19:00
60 min
Chiro masáž
Dorota Jurčáková
0949098300
dorotajurcakova1@gmail.com
Personál FYZIO&FIT
Potvrdené
piatok 3. apríla
09:00
10:00
60 min
Chiro masáž
Branislav Domonkoš
0948759333
branislavdomonkos@gmail.com
Personál FYZIO&FIT
Potvrdené
14:00
15:00
60 min
Chiro masáž
Lukas Friga
0949489545
frigalukas@gmail.com
Personál FYZIO&FIT



streda 8. apríla
12:30
13:30
60 min
Chiro masáž
Elena Horvatovič
+421944716718
eburdikova@sky.com
Personál FYZIO&FIT
Potvrdené
18:00
19:00
60 min
Chiro masáž
Laura Jurpaková
+421944171181
laura.jurpakova@gmail.com
Personál FYZIO&FIT
Potvrdené
štvrtok 9. apríla
10:00
10:30
30 min
Chiropraxia/Naprávanie
Kristína Strelová
+421915434160
kristina.strelova3@gmail.com
Personál FYZIO&FIT
Potvrdené
14:00
15:30
90 min
Celotelová chiro masáž
Zita Banikova
+421908396442
zitusbanikova@gmail.com
Personál FYZIO&FIT


streda 15. apríla
10:00
11:00
60 min
Chiro masáž
Natália Kandráčová
+421908657516
n.nociarova97@gmail.com
Personál FYZIO&FIT


###############

štvrtok 30. apríla
16:00
17:30
90 min
Celotelová chiro masáž
erik babcan
+421950491856
erikbabcan@gmail.com
Personál FYZIO&FIT

pondelok 4. mája
12:00
13:30
90 min
Celotelová chiro masáž
Patricia Senova
+352621528014
senopatricia@gmail.com
Personál FYZIO&FIT

Potvrdené
13:30
15:00
90 min
Celotelová chiro masáž
Pavol Seno
+352621528701
senopavol@icloud.com
Personál FYZIO&FIT