// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  const errorMsg = "KRITICKÁ CHYBA: Chýbajú Supabase environment premenné. Skontrolujte súbor .env a uistite sa, že obsahuje VITE_SUPABASE_URL a VITE_SUPABASE_ANON_KEY.";
  console.error(errorMsg);
  throw new Error(errorMsg);
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
